# Generated by Django 3.1.2 on 2021-03-20 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=75)),
                ('font_family', models.CharField(default='Arial, Helvetica, Sans Serif', max_length=75)),
                ('font_size', models.CharField(default='10pt', max_length=10)),
                ('current_theme', models.CharField(default='black', max_length=10)),
                ('navbar_bg_color', models.CharField(default='black', max_length=25)),
                ('navbar_fg_color', models.CharField(default='white', max_length=25)),
                ('navbar_button_fg_color', models.CharField(default='black', max_length=25)),
                ('navbar_button_bg_color', models.CharField(default='#e7e7e7', max_length=25)),
                ('navbar_button_border_color', models.CharField(default='white', max_length=25)),
                ('dropdown_fg_color', models.CharField(default='black', max_length=25)),
                ('dropdown_bg_color', models.CharField(default='#f9f9f9', max_length=25)),
                ('dropdown_hover_color', models.CharField(default='#dddddd', max_length=25)),
                ('menubar_bg_color', models.CharField(default='white', max_length=25)),
                ('tabbar_bg_color', models.CharField(default='white', max_length=25)),
                ('tabbar_fg_color', models.CharField(default='black', max_length=25)),
                ('tabbar_border_color', models.CharField(default='black', max_length=25)),
                ('tabbar_hover_bg_color', models.CharField(default='grey', max_length=25)),
                ('tabbar_hover_fg_color', models.CharField(default='white', max_length=25)),
                ('tabbar_active_bg_color', models.CharField(default='black', max_length=25)),
                ('tabbar_active_fg_color', models.CharField(default='white', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(default='', max_length=75)),
                ('ui_state', models.CharField(default='index', max_length=10)),
                ('sheet_id', models.CharField(default='Sheet_1', max_length=10)),
                ('current_theme', models.CharField(default='black', max_length=10)),
                ('font_family', models.CharField(default='Arial, Helvetica, Sans Serif', max_length=75)),
                ('font_size', models.CharField(default='10pt', max_length=10)),
                ('navbar_bg_color', models.CharField(default='black', max_length=25)),
                ('navbar_fg_color', models.CharField(default='white', max_length=25)),
                ('navbar_button_fg_color', models.CharField(default='black', max_length=25)),
                ('navbar_button_bg_color', models.CharField(default='#e7e7e7', max_length=25)),
                ('navbar_button_border_color', models.CharField(default='white', max_length=25)),
                ('dropdown_fg_color', models.CharField(default='black', max_length=25)),
                ('dropdown_bg_color', models.CharField(default='#f9f9f9', max_length=25)),
                ('dropdown_hover_color', models.CharField(default='#dddddd', max_length=25)),
                ('menubar_bg_color', models.CharField(default='white', max_length=25)),
                ('tabbar_bg_color', models.CharField(default='white', max_length=25)),
                ('tabbar_fg_color', models.CharField(default='black', max_length=25)),
                ('tabbar_border_color', models.CharField(default='black', max_length=25)),
                ('tabbar_hover_bg_color', models.CharField(default='grey', max_length=25)),
                ('tabbar_hover_fg_color', models.CharField(default='white', max_length=25)),
                ('tabbar_active_bg_color', models.CharField(default='black', max_length=25)),
                ('tabbar_active_fg_color', models.CharField(default='white', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_character', models.CharField(default='', max_length=75)),
                ('current_theme', models.CharField(default='black', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
